### ISSUE TITLE
Images on cards fall out of bottom

### ISSUE THREAD

**Issue by HerndonC** [Vets-Who-Code/march2021#224]
Possibly a padding issue or it just needs to be contained within the card 
![image](https://user-images.githubusercontent.com/78369970/113734513-63175b00-96c9-11eb-91c4-449df68414a7.png)

**Comment by HerndonC** [comment]
Resolution is 2560 x 1440

This seems to only be a problem on either this resolution or larger screens than normal computer screens.

**Comment by dtetreau251** [comment]
we need to adjust the media queries for larger screens
