### ISSUE TITLE
Format Card Components

### ISSUE THREAD

**Issue by joeromine** [Vets-Who-Code/march2021#442]
Job Data Is sent to the cards but needs to be displayed. Use CSS from the MVP to style

**Comment by stephanlamoureux** [comment]
Most sections are complete, need to add:
- Remote: yes/no
- Days since posted

**Comment by stephanlamoureux** [comment]
Date is displayed but needs to be formatted, probably with toLocalDateString(). 
Remote is being displayed but the ternary is not working properly.
