### ISSUE TITLE
Adjust scroll points on search and pagination. Add smooth scroll. 

### ISSUE THREAD

**Issue by dtetreau251** [Vets-Who-Code/march2021#481]

**Comment by stephanlamoureux** [comment]
I fixed the scrollpoints, wasn't able to get the smooth scroll to work on the job search page only and not the entire website (they don't use it)

**Comment by stephanlamoureux** [comment]
Possibilities:
- [react-scroll](https://www.digitalocean.com/community/tutorials/how-to-implement-smooth-scrolling-in-react)
- [gatsby-plugin-anchor-links](https://www.gatsbyjs.com/plugins/gatsby-plugin-anchor-links/)
