### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by dtetreau251** [Vets-Who-Code/march2021#91]
Steve is assigned to media queries to make the site more responsive

**Comment by dtetreau251** [comment]
steve has completed this. improvements are pending.

**Comment by stephanlamoureux** [comment]
This is what's left so far, and then with the hamburger menu we should be all set until new content is added:

- the padding needs to be lowered in the about me section for some portions of the media queries. 
- new cards aren't responsive
- the footer now changes random colors and font changes on resize?
