### ISSUE TITLE
Style the zombie radar button and make improvements

### ISSUE THREAD

**Issue by dtetreau251** [Vets-Who-Code/march2021#92]
Clinton is assigned

**Comment by stephanlamoureux** [comment]
Added styling to match the nav button. Probably could use a header or something.

**Comment by dtetreau251** [comment]
I sent Clinton information on a Google Map API. Maybe we could incorporate that.

**Comment by dtetreau251** [comment]
zombie radar button was changed and included in the zombie tools cards
